- name: Home 
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday
        - type: weather
          units: imperial
          hour-format: 24h
          location: Edinburgh, United Kingdom
    - size: full
      widgets:
        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: ^IXIC 
              name: NASDAQ
            - symbol: ^VIX
              name: VIX
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Seafile 
              url: https://seafile.carsonferreira.com
              icon: sh:seafile
            - title: Plex
              url: https://plex.carsonferreira.com
              icon: sh:plex
            - title: Immich
              url: https://photos.carsonferreira.com
              icon: sh:immich
        - type: server-stats
          servers:
            - type: local
              name: Hades
              mountpoints:
                # because root is not mounted in docker, use an alternative dir to see disk usage
                "/app/config":
                  name: Root