- name: Home2
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday
        - type: weather
          units: imperial
          hour-format: 24h
          location: Edinburgh, United Kingdom
    - size: full
      widgets:
        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: ^IXIC 
              name: NASDAQ
            - symbol: ^VIX
              name: VIX
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Seafile 
              url: https://seafile.carsonferreira.com
            - title: Plex
              url: https://plex.carsonferreira.com
            - title: Immich
              url: https://photos.carsonferreira.com
              icon: /assets/immich-logo.png
        - type: server-stats
          servers:
            - type: local
              name: Hades