- name: Home 
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday
        - type: weather
          units: imperial
          hour-format: 24h
          location: Edinburgh, United Kingdom
    - size: full
      widgets:
        - type: markets
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: ^IXIC 
              name: NASDAQ
            - symbol: ^VIX
              name: VIX
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Seafile 
              url: https://seafile.carsonferreira.com
              icon: sh:seafile
            - title: Plex
              url: https://plex.carsonferreira.com
              icon: sh:plex
            - title: Immich
              url: https://photos.carsonferreira.com
              icon: sh:immich
            # these Wireguard addresses need to be env vars at some point
            # gonna have to change them when I go back home
            - title: Radarr
              url: http://10.1.0.2:7878
              icon: sh:radarr
            - title: Sonarr
              url: http://10.1.0.2:8989
              icon: sh:sonarr
            - title: qBittorrent
              url: http://10.1.0.2:20480
              icon: sh:qBittorrent
            - title: Portainer
              url: https://10.1.0.2:9443
              icon: sh:portainer
        - type: server-stats
          servers:
            - type: local
              name: Hades
              # because root is not mounted in docker, use an alternative dir to see disk usage
              hide-mountpoints-by-default: true
              mountpoints:
                "/app/config":
                  name: Root
                  hide: false