- name: Home 
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday
        - type: weather
          units: imperial
          hour-format: 24h
          location: Edinburgh, United Kingdom
    - size: full
      widgets:
        - type: bookmarks
          groups:
            - title: Apps
              links:
                - title: Protonmail
                  url: https://mail.proton.me/u/0/inbox
                  icon: sh:proton-mail
                - title: Edinburgh myEd
                  url: https://www.myed.ed.ac.uk/uPortal/Login?refUrl=%2Fmyed-progressive%2F
                  icon: https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/University_of_Edinburgh_ceremonial_roundel.svg/1280px-University_of_Edinburgh_ceremonial_roundel.svg.png
            - title: News
              links:
                - title: AP News
                  url: https://apnews.com/
                  icon: https://assets.apnews.com/19/66/bc546486408c8595f01753a9fbeb/ap-logo-176-by-208.svg
                - title: Financial Times
                  url: https://ft.com
                  icon: https://www.ft.com/__origami/service/image/v2/images/raw/ftlogo-v1%3Abrand-ft-logo-square-coloured?source=image-url-builder
                - title: BBC
                  url: https://bbc.co.uk
                  icon: https://icon2.cleanpng.com/20180629/fw/aayfx7yzb.webp
                - title: New York Times
                  url: https://nytimes.com
                  icon: sh:the-new-york-times
                - title: Reuters
                  url: https://reuters.com
                  icon: https://static.wikia.nocookie.net/logopedia/images/5/53/Reuters_2008_vertical.svg/revision/latest?cb=20240525053744
                - title: Wall Street Journal
                  url: https://wsj.com
                  icon: https://images.icon-icons.com/2699/PNG/512/wsj_logo_icon_168755.png
        - type: markets
          chart-link-template: https://finance.yahoo.com/quote/{SYMBOL}/
          symbol-link-template: https://finance.yahoo.com/quote/{SYMBOL}/
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: ^IXIC 
              name: NASDAQ
            - symbol: ^VIX
              name: VIX
            - symbol: EUAD
              name: STOXX Europe Defense
            - symbol: VGK
              name: Vanguard Europe ETF
            - symbol: GC=F
              name: Gold
        - type: videos
          style: grid-cards
          channels:
            # Big A
            - UCdBXOyqr8cDshsp7kcKDAkg
            # Atrioc
            - UCgv4dPk_qZNAbUW9WkuLPSA
            # GOAT (basketball)
            - UC27JCqpAz5DZHS5uYiCMfOw
            # NFL Highlights
            - UCDVYQ4Zhbm3S2dlz7P1GBDg
            # F1 Highlights
            - UCB_qr75-ydFVKSF9Dmo6izg
            # Fireship (tech news)
            - UCsBjURrPoezykLs9EqgamOA
            # Hank Green
            - UCOT2iLov0V7Re7ku_3UBtcQ
            # SciShow
            - UCZYTClx2T1of7BRZ86-8fow
            # Good Work
            - UC_-hYjoNe4PJNFa9iZ4lraA
            # Channel 5
            - UC-AQKm7HUNMmxjdS371MSwg
            # Jolly
            - UCOgGAfSUy5LvEyVS_LF5kdw
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Seafile 
              url: https://seafile.carsonferreira.com
              icon: sh:seafile
            - title: Plex
              url: https://plex.carsonferreira.com
              icon: sh:plex
              # plex returns 401 unauthorized when up
              alt-status-codes:
                - 401
            - title: Immich
              url: https://photos.carsonferreira.com
              icon: sh:immich
            # these Wireguard addresses need to be env vars at some point
            # gonna have to change them when I go back home
            - title: Radarr
              url: http://10.1.0.2:7878
              icon: sh:radarr
            - title: Sonarr
              url: http://10.1.0.2:8989
              icon: sh:sonarr
            - title: qBittorrent
              url: http://10.1.0.2:20480
              icon: sh:qbittorrent
            - title: Portainer
              url: https://10.1.0.2:9443
              icon: sh:portainer
              allow-insecure: true
        - type: server-stats
          servers:
            - type: local
              name: Hades
              # because root is not mounted in docker, use an alternative dir to see disk usage
              hide-mountpoints-by-default: true
              mountpoints:
                "/app/config":
                  name: Root
                  hide: false